### ISSUE TITLE
[help] node project - run tests?

### ISSUE THREAD

**Issue by hermann-p** [nix-community/dream2nix#220]
My node (TypeScript) project builds just fine with a minimal `dream2nix`-config from the examples (and I'm amazed at how easy and clutter-free it is compared to other node nixification tools!).  
Now I'd like to run the flake from a git workflow using `nixbuild/nix-quick-install-action@v14`. The project has a common pattern for node apps:

```json 
"scripts": {
  "build": "tsc",
  "test": "jest"
  }
```

The `build` script gets called successfully from commandline and from the git-workflow

```yaml
name: Test
on: [pull_request, push]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nixbuild/nix-quick-install-action@v14
        with:
          nix_conf: experimental-features = nix-command flakes
      - name: build packages
        run: nix build '.#default'
```

Now I'd also like to run the task `test`, so I can use the workflow's exit state as complete sanity check, but I can't find a way to do so.

- When modifying my build command to `npm run test; tsc` or adding a postbuild command, the test will fail because it can't find any test files (test files are in the `./src/` folder and identified by a `xxx.test.ts` substring).
- When adding an "app" to flakes that runs the `jest` executable from the result, it will fail due to missing dependencies, namely `ts-jest not found`.

I think the latter might be fixable by moving all node dev-dependencies to runtime dependencies, but this would negatively impact the distributed package's size and dependency graph.

Is there some misconception I have about the working of `dream2nix`? How should I go about, fixing this?

[The repository in question](https://github.com/campudus/grud-devtools)
