### ISSUE TITLE
[pip-freeze] Error: no `requirements-dev.txt`

### ISSUE THREAD

**Issue by augustebaum** [nix-community/dream2nix#521]
Hi,

I'm trying out `dream2nix` with little experience with Nix. I have a `requirements.txt` file and would like to make a flake out of it. However, when I build or try to enter a shell based on the flake, I get the following error:
```sh
❯ nix shell 'github:augustebaum/dream2nix-test'
error: getting status of '/nix/store/p6q0w6pd8w08v1pbwiq8aakq03mwksf2-source/requirements-dev.txt': No such file or directory
(use '--show-trace' to show detailed location information)
```

I couldn't find anything about this on the "10-minute" tutorial or elsewhere; is this normal? If so, can anyone tell me what I'm doing wrong? Link to the repo: https://github.com/augustebaum/dream2nix-test. 

Thanks in advance for your support! Quite excited about dream2nix apart from that :)

**Comment by con-f-use** [comment]
Did you `git add requirements-dev.txt`? Nothing that git doesn't know about is kown to flakes.

**Comment by con-f-use** [comment]
Update: I did manage do get it to do something:

```nix
# flake.nix
{
  inputs = { dream2nix.url = "github:nix-community/dream2nix"; };

  outputs = { self, dream2nix, } @ inp: dream2nix.lib.makeFlakeOutputs {
    systems = ["x86_64-linux"];
    config.projectRoot = ./.;
    source = ./.;
    projects = ./projects.toml;
  };
}
```

```toml
# projects.toml
[main]
name = "main"
relPath = ""
subsystem = "python"
translator = "pip"

[main.subsystemInfo]
pythonAttr = "python3"
extraSetupDeps = [ "-r source/requirements.txt" ]
pythonVersion = "3.9"
```

So the trick is to use the impure `"pip"` translator and `extraSetupDeps`. In addition to these files, I had to commit an empty `pyprojects.toml` and my `requirements.txt`. Then I can run `nix build './#resolveImpure'`, which does a lot of piping for each of my dependencies. Then it fails for one of them. :cry:
