### ISSUE TITLE
Add minimal local Rust example

### ISSUE THREAD

**Issue by malteneuss** [nix-community/dream2nix#546]
I'm trying to package a small Rust project within NixOS and really like that just works (build and package) with minimal Nix code.

Having tried dream2nix (Rust within NixOS in general) for the first time i believe a minimal, local Rust example would have helped me a lot. I would like to add PR with such an example project with some explanation. Would a small hello-world example like the following be ok?

```nix
# flake.nix
{
  description = "Minimal Rust dream2nix example";
  inputs = {
      nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
      dream2nix.url = "github:nix-community/dream2nix";
      dream2nix.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = { self, dream2nix }:
        dream2nix.lib.makeFlakeOutputs {
              systems = ["x86_64-linux"];
              config.projectRoot = ./.;
              source = ./.;
              projects."rust-nixos" = {
                  name = "rust-nixos";
                  subsystem = "rust";
                  translator = "cargo-lock";
              };
              # With Rust workspaces better run auto-detection
              # "nix run github:nix-community/dream2nix#detect-projects ."
              # to generate a `projects.toml` file to reference here:
              # projects = ./projects.toml;
        };
}
```

```toml
# projects.toml
[rust-dream2nix]
name = "rust-dream2nix"
subsystem = "rust"
translator = "cargo-lock"
# optional settings
# relPath = ""
# translators = [ "cargo-lock", "cargo-toml",]
# builder = "crane"
```

If ok, should this be an example with its own folder in https://github.com/nix-community/dream2nix/tree/main/examples, or be listed in the docs https://nix-community.github.io/dream2nix/subsystems/rust.html?
Also i've seen some example using fennix. When would that be useful, since crane (the current default builder) seems to be working fine.
