### ISSUE TITLE
PDM - Build fails with some dependencies

### ISSUE THREAD

**Issue by JonBoyleCoding** [nix-community/dream2nix#785]
I've had a few dependencies that fail to build with the WIP pdm module at the same point.

- python-jwt
- paho-mqtt

I've used the example project in this repo, and just done `pdm add` with the relevant package and when building the package fails.

````
error: A definition for option `pdm.sourceSelector.<function body>' is not of type `string'. Definition values:
       - In `/nix/store/5vgzjcl7wrjpi942cffsr3q6zj5nwszd-source/modules/dream2nix/WIP-python-pdm': null
(use '--show-trace' to show detailed location information)
```

The full trace: https://gist.github.com/JonBoyleCoding/461e3a2fb3fa9ba59e50003a6bd1dca9

I thought at first it was projects with hypens, but the `in-place` package seems to work fine so that's not it.

I'm on dream2nix 24e81d5ce81881089ac757495ab5e0bcf7d5df79. Here an example pyproject.toml that seems to fail

```toml
[project]
name = "my-project"
version = "0.1.0"
description = ""
dependencies = [
    "requests>=2.31.0",
    "python-jwt>=4.0.0",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[project.scripts]
my-script = "my_project:main"

[project.optional-dependencies]
dev = [
    "pi>=0.1.2",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
```
