### ISSUE TITLE
integrate dream2nix with pyproject.toml

### ISSUE THREAD

**Issue by DavHau** [nix-community/dream2nix#816]
For single language use-cases it could be interesting to integrate dream2nix with pyproject.toml, so that the following workflow becomes possible:

### Workflow

```
$ pip install dream2nix
```
```
$ dream2nix init
```
which will ensure nix is installed and modify the `pyproject.toml` to include the following
```toml
[build-system]
requires = ["dream2nix"]
```

Then enter the dev shell via:
```
dream2nix develop
```

Or build the project via
```
dream2nix build
```

... where the `dream2nix` executable is a simple wrapper around nix which `imagines` a `flake.nix` into existence before executing nix with the given `"$@"` args.

### Customization
Instead of modifying a default.nix template, the nix build can be customized via the `pyproject.toml`
```toml
[tool.dream2nix]
mkDerivation.preBuild = ""
buildPythonPackage.pythonImportsCheck = ["my_tool"]
```
